/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as IndexRouteImport } from './routes/index'

const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clock'
  id: '__root__' | '/' | '/clock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClockRoute: typeof ClockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClockRoute: ClockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
